version: '3'
services:
  db:
    image: mysql:5.7
    container_name: sandbox_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld
    volumes:
    - db_data:/var/lib/mysql
    - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    - ./seeds:/seeds
    ports:
    - 33060:3306

volumes:
  db_data:
    driver: local
